config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  resources :tweets
 
  delete 'tweets/:id', to: 'tweets#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  has_one_attached :image
  validates :message, presence: { message: "メッセージが空です" }, length: { maximum: 140, message: "メッセージは140文字以内にしてください" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Tweet.all

  end

  def show
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.tdate = Time.current
    

    if @tweet.save
      redirect_to @tweet, notice: 'ツイートが作成されました'
    else
      redirect_to @tweet, notice: 'メッセージが空か、140文字を超えています'
    end
  end

  def edit
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'ツイートが更新されました'
    else
      redirect_to @tweet, notice: 'メッセージが空か、140文字を超えています'
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to '/'
  end
  


  private
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:message, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <title>TwitterClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  



  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/edit.html.erb
<h1><%= action_name == 'new' ? '新しいツイート' : 'ツイートを編集する' %></h1>

<%= form_with(model: @tweet, local: true) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> が発生しました:</h2>
      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %><br>
    <%= form.text_area :message %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to '一覧に戻る', tweets_path %>

app/views/tweets/index.html.erb
<h1>ツイート一覧</h1>
<%= link_to '新しいツイート', new_tweet_path %>
<ul>
  <% @tweets.each do |tweet| %>
    <li>
      <%= tweet.message %> - <%= distance_of_time_in_words(tweet.tdate, Time.current, include_seconds: true) %> 前
      
      <% if tweet.image.attached? %>
        <%= image_tag tweet.image %>
        <p><%= tweet.image.filename %></p> <!-- 画像のファイル名を表示 -->
      <% end %>
      
      <%= link_to '詳細', tweet_path(tweet) %>
      <%= link_to '編集', edit_tweet_path(tweet) %>
      <%= link_to '削除', "/tweets/#{tweet.id}", data: {turbo_method: :delete} %>
    </li>
  <% end %>
</ul>

app/views/tweets/new.html.erb
<h1><%= action_name == 'new' ? '新しいツイート' : 'ツイートを編集する' %></h1>

<%= form_with(model: @tweet, local: true) do |form| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> が発生しました:</h2>
      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %><br>
    <%= form.text_area :message %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to '一覧に戻る', tweets_path %>

app/views/tweets/show.html.erb
<h1>ツイート詳細</h1>
<p><%= @tweet.message %></p>
<p>投稿時間: <%= time_ago_in_words(@tweet.tdate) %>前</p>
<% if @tweet.image.attached? %>
  <div>
    <%= image_tag @tweet.image %>
  </div>
<% end %>
<%= link_to '編集', edit_tweet_path(@tweet) %>
<%= link_to '削除', "/tweets/#{@tweet.id}", data: {turbo_method: :delete} %>
<%= link_to '一覧に戻る', tweets_path %>